// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Fetch a partition from an executor
   * </pre>
   *
   * <code>.ballista.protobuf.FetchPartition fetch_partition = 3;</code>
   * @return Whether the fetchPartition field is set.
   */
  boolean hasFetchPartition();
  /**
   * <pre>
   * Fetch a partition from an executor
   * </pre>
   *
   * <code>.ballista.protobuf.FetchPartition fetch_partition = 3;</code>
   * @return The fetchPartition.
   */
  org.ballistacompute.protobuf.FetchPartition getFetchPartition();
  /**
   * <pre>
   * Fetch a partition from an executor
   * </pre>
   *
   * <code>.ballista.protobuf.FetchPartition fetch_partition = 3;</code>
   */
  org.ballistacompute.protobuf.FetchPartitionOrBuilder getFetchPartitionOrBuilder();

  /**
   * <pre>
   * configuration settings
   * </pre>
   *
   * <code>repeated .ballista.protobuf.KeyValuePair settings = 100;</code>
   */
  java.util.List<org.ballistacompute.protobuf.KeyValuePair> 
      getSettingsList();
  /**
   * <pre>
   * configuration settings
   * </pre>
   *
   * <code>repeated .ballista.protobuf.KeyValuePair settings = 100;</code>
   */
  org.ballistacompute.protobuf.KeyValuePair getSettings(int index);
  /**
   * <pre>
   * configuration settings
   * </pre>
   *
   * <code>repeated .ballista.protobuf.KeyValuePair settings = 100;</code>
   */
  int getSettingsCount();
  /**
   * <pre>
   * configuration settings
   * </pre>
   *
   * <code>repeated .ballista.protobuf.KeyValuePair settings = 100;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.KeyValuePairOrBuilder> 
      getSettingsOrBuilderList();
  /**
   * <pre>
   * configuration settings
   * </pre>
   *
   * <code>repeated .ballista.protobuf.KeyValuePair settings = 100;</code>
   */
  org.ballistacompute.protobuf.KeyValuePairOrBuilder getSettingsOrBuilder(
      int index);

  public org.ballistacompute.protobuf.Action.ActionTypeCase getActionTypeCase();
}
