// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

/**
 * Protobuf type {@code ballista.protobuf.CompletedJob}
 */
public final class CompletedJob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ballista.protobuf.CompletedJob)
    CompletedJobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompletedJob.newBuilder() to construct.
  private CompletedJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompletedJob() {
    partitionLocation_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompletedJob();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompletedJob(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              partitionLocation_ = new java.util.ArrayList<org.ballistacompute.protobuf.PartitionLocation>();
              mutable_bitField0_ |= 0x00000001;
            }
            partitionLocation_.add(
                input.readMessage(org.ballistacompute.protobuf.PartitionLocation.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        partitionLocation_ = java.util.Collections.unmodifiableList(partitionLocation_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_CompletedJob_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_CompletedJob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ballistacompute.protobuf.CompletedJob.class, org.ballistacompute.protobuf.CompletedJob.Builder.class);
  }

  public static final int PARTITION_LOCATION_FIELD_NUMBER = 1;
  private java.util.List<org.ballistacompute.protobuf.PartitionLocation> partitionLocation_;
  /**
   * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.ballistacompute.protobuf.PartitionLocation> getPartitionLocationList() {
    return partitionLocation_;
  }
  /**
   * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.ballistacompute.protobuf.PartitionLocationOrBuilder> 
      getPartitionLocationOrBuilderList() {
    return partitionLocation_;
  }
  /**
   * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
   */
  @java.lang.Override
  public int getPartitionLocationCount() {
    return partitionLocation_.size();
  }
  /**
   * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.PartitionLocation getPartitionLocation(int index) {
    return partitionLocation_.get(index);
  }
  /**
   * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.PartitionLocationOrBuilder getPartitionLocationOrBuilder(
      int index) {
    return partitionLocation_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < partitionLocation_.size(); i++) {
      output.writeMessage(1, partitionLocation_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < partitionLocation_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, partitionLocation_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ballistacompute.protobuf.CompletedJob)) {
      return super.equals(obj);
    }
    org.ballistacompute.protobuf.CompletedJob other = (org.ballistacompute.protobuf.CompletedJob) obj;

    if (!getPartitionLocationList()
        .equals(other.getPartitionLocationList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPartitionLocationCount() > 0) {
      hash = (37 * hash) + PARTITION_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionLocationList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.CompletedJob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ballistacompute.protobuf.CompletedJob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ballista.protobuf.CompletedJob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ballista.protobuf.CompletedJob)
      org.ballistacompute.protobuf.CompletedJobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_CompletedJob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_CompletedJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ballistacompute.protobuf.CompletedJob.class, org.ballistacompute.protobuf.CompletedJob.Builder.class);
    }

    // Construct using org.ballistacompute.protobuf.CompletedJob.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPartitionLocationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (partitionLocationBuilder_ == null) {
        partitionLocation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        partitionLocationBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_CompletedJob_descriptor;
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.CompletedJob getDefaultInstanceForType() {
      return org.ballistacompute.protobuf.CompletedJob.getDefaultInstance();
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.CompletedJob build() {
      org.ballistacompute.protobuf.CompletedJob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.CompletedJob buildPartial() {
      org.ballistacompute.protobuf.CompletedJob result = new org.ballistacompute.protobuf.CompletedJob(this);
      int from_bitField0_ = bitField0_;
      if (partitionLocationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          partitionLocation_ = java.util.Collections.unmodifiableList(partitionLocation_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.partitionLocation_ = partitionLocation_;
      } else {
        result.partitionLocation_ = partitionLocationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ballistacompute.protobuf.CompletedJob) {
        return mergeFrom((org.ballistacompute.protobuf.CompletedJob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ballistacompute.protobuf.CompletedJob other) {
      if (other == org.ballistacompute.protobuf.CompletedJob.getDefaultInstance()) return this;
      if (partitionLocationBuilder_ == null) {
        if (!other.partitionLocation_.isEmpty()) {
          if (partitionLocation_.isEmpty()) {
            partitionLocation_ = other.partitionLocation_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePartitionLocationIsMutable();
            partitionLocation_.addAll(other.partitionLocation_);
          }
          onChanged();
        }
      } else {
        if (!other.partitionLocation_.isEmpty()) {
          if (partitionLocationBuilder_.isEmpty()) {
            partitionLocationBuilder_.dispose();
            partitionLocationBuilder_ = null;
            partitionLocation_ = other.partitionLocation_;
            bitField0_ = (bitField0_ & ~0x00000001);
            partitionLocationBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionLocationFieldBuilder() : null;
          } else {
            partitionLocationBuilder_.addAllMessages(other.partitionLocation_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.ballistacompute.protobuf.CompletedJob parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.ballistacompute.protobuf.CompletedJob) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.ballistacompute.protobuf.PartitionLocation> partitionLocation_ =
      java.util.Collections.emptyList();
    private void ensurePartitionLocationIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        partitionLocation_ = new java.util.ArrayList<org.ballistacompute.protobuf.PartitionLocation>(partitionLocation_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.ballistacompute.protobuf.PartitionLocation, org.ballistacompute.protobuf.PartitionLocation.Builder, org.ballistacompute.protobuf.PartitionLocationOrBuilder> partitionLocationBuilder_;

    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public java.util.List<org.ballistacompute.protobuf.PartitionLocation> getPartitionLocationList() {
      if (partitionLocationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partitionLocation_);
      } else {
        return partitionLocationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public int getPartitionLocationCount() {
      if (partitionLocationBuilder_ == null) {
        return partitionLocation_.size();
      } else {
        return partitionLocationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public org.ballistacompute.protobuf.PartitionLocation getPartitionLocation(int index) {
      if (partitionLocationBuilder_ == null) {
        return partitionLocation_.get(index);
      } else {
        return partitionLocationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder setPartitionLocation(
        int index, org.ballistacompute.protobuf.PartitionLocation value) {
      if (partitionLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionLocationIsMutable();
        partitionLocation_.set(index, value);
        onChanged();
      } else {
        partitionLocationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder setPartitionLocation(
        int index, org.ballistacompute.protobuf.PartitionLocation.Builder builderForValue) {
      if (partitionLocationBuilder_ == null) {
        ensurePartitionLocationIsMutable();
        partitionLocation_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionLocationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder addPartitionLocation(org.ballistacompute.protobuf.PartitionLocation value) {
      if (partitionLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionLocationIsMutable();
        partitionLocation_.add(value);
        onChanged();
      } else {
        partitionLocationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder addPartitionLocation(
        int index, org.ballistacompute.protobuf.PartitionLocation value) {
      if (partitionLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionLocationIsMutable();
        partitionLocation_.add(index, value);
        onChanged();
      } else {
        partitionLocationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder addPartitionLocation(
        org.ballistacompute.protobuf.PartitionLocation.Builder builderForValue) {
      if (partitionLocationBuilder_ == null) {
        ensurePartitionLocationIsMutable();
        partitionLocation_.add(builderForValue.build());
        onChanged();
      } else {
        partitionLocationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder addPartitionLocation(
        int index, org.ballistacompute.protobuf.PartitionLocation.Builder builderForValue) {
      if (partitionLocationBuilder_ == null) {
        ensurePartitionLocationIsMutable();
        partitionLocation_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionLocationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder addAllPartitionLocation(
        java.lang.Iterable<? extends org.ballistacompute.protobuf.PartitionLocation> values) {
      if (partitionLocationBuilder_ == null) {
        ensurePartitionLocationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partitionLocation_);
        onChanged();
      } else {
        partitionLocationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder clearPartitionLocation() {
      if (partitionLocationBuilder_ == null) {
        partitionLocation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        partitionLocationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public Builder removePartitionLocation(int index) {
      if (partitionLocationBuilder_ == null) {
        ensurePartitionLocationIsMutable();
        partitionLocation_.remove(index);
        onChanged();
      } else {
        partitionLocationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public org.ballistacompute.protobuf.PartitionLocation.Builder getPartitionLocationBuilder(
        int index) {
      return getPartitionLocationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public org.ballistacompute.protobuf.PartitionLocationOrBuilder getPartitionLocationOrBuilder(
        int index) {
      if (partitionLocationBuilder_ == null) {
        return partitionLocation_.get(index);  } else {
        return partitionLocationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public java.util.List<? extends org.ballistacompute.protobuf.PartitionLocationOrBuilder> 
         getPartitionLocationOrBuilderList() {
      if (partitionLocationBuilder_ != null) {
        return partitionLocationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partitionLocation_);
      }
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public org.ballistacompute.protobuf.PartitionLocation.Builder addPartitionLocationBuilder() {
      return getPartitionLocationFieldBuilder().addBuilder(
          org.ballistacompute.protobuf.PartitionLocation.getDefaultInstance());
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public org.ballistacompute.protobuf.PartitionLocation.Builder addPartitionLocationBuilder(
        int index) {
      return getPartitionLocationFieldBuilder().addBuilder(
          index, org.ballistacompute.protobuf.PartitionLocation.getDefaultInstance());
    }
    /**
     * <code>repeated .ballista.protobuf.PartitionLocation partition_location = 1;</code>
     */
    public java.util.List<org.ballistacompute.protobuf.PartitionLocation.Builder> 
         getPartitionLocationBuilderList() {
      return getPartitionLocationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.ballistacompute.protobuf.PartitionLocation, org.ballistacompute.protobuf.PartitionLocation.Builder, org.ballistacompute.protobuf.PartitionLocationOrBuilder> 
        getPartitionLocationFieldBuilder() {
      if (partitionLocationBuilder_ == null) {
        partitionLocationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.ballistacompute.protobuf.PartitionLocation, org.ballistacompute.protobuf.PartitionLocation.Builder, org.ballistacompute.protobuf.PartitionLocationOrBuilder>(
                partitionLocation_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        partitionLocation_ = null;
      }
      return partitionLocationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ballista.protobuf.CompletedJob)
  }

  // @@protoc_insertion_point(class_scope:ballista.protobuf.CompletedJob)
  private static final org.ballistacompute.protobuf.CompletedJob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ballistacompute.protobuf.CompletedJob();
  }

  public static org.ballistacompute.protobuf.CompletedJob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompletedJob>
      PARSER = new com.google.protobuf.AbstractParser<CompletedJob>() {
    @java.lang.Override
    public CompletedJob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompletedJob(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompletedJob> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompletedJob> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ballistacompute.protobuf.CompletedJob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

