// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface CsvFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.CsvFormat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool has_header = 1;</code>
   * @return The hasHeader.
   */
  boolean getHasHeader();

  /**
   * <code>string delimiter = 2;</code>
   * @return The delimiter.
   */
  java.lang.String getDelimiter();
  /**
   * <code>string delimiter = 2;</code>
   * @return The bytes for delimiter.
   */
  com.google.protobuf.ByteString
      getDelimiterBytes();
}
