// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface FileGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.FileGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ballista.protobuf.PartitionedFile files = 1;</code>
   */
  java.util.List<org.ballistacompute.protobuf.PartitionedFile> 
      getFilesList();
  /**
   * <code>repeated .ballista.protobuf.PartitionedFile files = 1;</code>
   */
  org.ballistacompute.protobuf.PartitionedFile getFiles(int index);
  /**
   * <code>repeated .ballista.protobuf.PartitionedFile files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .ballista.protobuf.PartitionedFile files = 1;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.PartitionedFileOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .ballista.protobuf.PartitionedFile files = 1;</code>
   */
  org.ballistacompute.protobuf.PartitionedFileOrBuilder getFilesOrBuilder(
      int index);
}
