// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface GetFileMetadataParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.GetFileMetadataParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>.ballista.protobuf.FileType file_type = 2;</code>
   * @return The enum numeric value on the wire for fileType.
   */
  int getFileTypeValue();
  /**
   * <code>.ballista.protobuf.FileType file_type = 2;</code>
   * @return The fileType.
   */
  org.ballistacompute.protobuf.FileType getFileType();
}
