// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface HashJoinExecNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.HashJoinExecNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.PhysicalPlanNode left = 1;</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>.ballista.protobuf.PhysicalPlanNode left = 1;</code>
   * @return The left.
   */
  org.ballistacompute.protobuf.PhysicalPlanNode getLeft();
  /**
   * <code>.ballista.protobuf.PhysicalPlanNode left = 1;</code>
   */
  org.ballistacompute.protobuf.PhysicalPlanNodeOrBuilder getLeftOrBuilder();

  /**
   * <code>.ballista.protobuf.PhysicalPlanNode right = 2;</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>.ballista.protobuf.PhysicalPlanNode right = 2;</code>
   * @return The right.
   */
  org.ballistacompute.protobuf.PhysicalPlanNode getRight();
  /**
   * <code>.ballista.protobuf.PhysicalPlanNode right = 2;</code>
   */
  org.ballistacompute.protobuf.PhysicalPlanNodeOrBuilder getRightOrBuilder();

  /**
   * <code>repeated .ballista.protobuf.JoinOn on = 3;</code>
   */
  java.util.List<org.ballistacompute.protobuf.JoinOn> 
      getOnList();
  /**
   * <code>repeated .ballista.protobuf.JoinOn on = 3;</code>
   */
  org.ballistacompute.protobuf.JoinOn getOn(int index);
  /**
   * <code>repeated .ballista.protobuf.JoinOn on = 3;</code>
   */
  int getOnCount();
  /**
   * <code>repeated .ballista.protobuf.JoinOn on = 3;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.JoinOnOrBuilder> 
      getOnOrBuilderList();
  /**
   * <code>repeated .ballista.protobuf.JoinOn on = 3;</code>
   */
  org.ballistacompute.protobuf.JoinOnOrBuilder getOnOrBuilder(
      int index);

  /**
   * <code>.ballista.protobuf.JoinType join_type = 4;</code>
   * @return The enum numeric value on the wire for joinType.
   */
  int getJoinTypeValue();
  /**
   * <code>.ballista.protobuf.JoinType join_type = 4;</code>
   * @return The joinType.
   */
  org.ballistacompute.protobuf.JoinType getJoinType();

  /**
   * <code>.ballista.protobuf.PartitionMode partition_mode = 6;</code>
   * @return The enum numeric value on the wire for partitionMode.
   */
  int getPartitionModeValue();
  /**
   * <code>.ballista.protobuf.PartitionMode partition_mode = 6;</code>
   * @return The partitionMode.
   */
  org.ballistacompute.protobuf.PartitionMode getPartitionMode();

  /**
   * <code>bool null_equals_null = 7;</code>
   * @return The nullEqualsNull.
   */
  boolean getNullEqualsNull();
}
