// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

/**
 * Protobuf enum {@code ballista.protobuf.JoinConstraint}
 */
public enum JoinConstraint
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ON = 0;</code>
   */
  ON(0),
  /**
   * <code>USING = 1;</code>
   */
  USING(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ON = 0;</code>
   */
  public static final int ON_VALUE = 0;
  /**
   * <code>USING = 1;</code>
   */
  public static final int USING_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static JoinConstraint valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static JoinConstraint forNumber(int value) {
    switch (value) {
      case 0: return ON;
      case 1: return USING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JoinConstraint>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JoinConstraint> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JoinConstraint>() {
          public JoinConstraint findValueByNumber(int number) {
            return JoinConstraint.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.ballistacompute.protobuf.BallistaProto.getDescriptor().getEnumTypes().get(7);
  }

  private static final JoinConstraint[] VALUES = values();

  public static JoinConstraint valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JoinConstraint(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ballista.protobuf.JoinConstraint)
}

