// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface NotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.Not)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.LogicalExprNode expr = 1;</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <code>.ballista.protobuf.LogicalExprNode expr = 1;</code>
   * @return The expr.
   */
  org.ballistacompute.protobuf.LogicalExprNode getExpr();
  /**
   * <code>.ballista.protobuf.LogicalExprNode expr = 1;</code>
   */
  org.ballistacompute.protobuf.LogicalExprNodeOrBuilder getExprOrBuilder();
}
