// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface PartitionLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.PartitionLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.PartitionId partition_id = 1;</code>
   * @return Whether the partitionId field is set.
   */
  boolean hasPartitionId();
  /**
   * <code>.ballista.protobuf.PartitionId partition_id = 1;</code>
   * @return The partitionId.
   */
  org.ballistacompute.protobuf.PartitionId getPartitionId();
  /**
   * <code>.ballista.protobuf.PartitionId partition_id = 1;</code>
   */
  org.ballistacompute.protobuf.PartitionIdOrBuilder getPartitionIdOrBuilder();

  /**
   * <code>.ballista.protobuf.ExecutorMetadata executor_meta = 2;</code>
   * @return Whether the executorMeta field is set.
   */
  boolean hasExecutorMeta();
  /**
   * <code>.ballista.protobuf.ExecutorMetadata executor_meta = 2;</code>
   * @return The executorMeta.
   */
  org.ballistacompute.protobuf.ExecutorMetadata getExecutorMeta();
  /**
   * <code>.ballista.protobuf.ExecutorMetadata executor_meta = 2;</code>
   */
  org.ballistacompute.protobuf.ExecutorMetadataOrBuilder getExecutorMetaOrBuilder();

  /**
   * <code>.ballista.protobuf.PartitionStats partition_stats = 3;</code>
   * @return Whether the partitionStats field is set.
   */
  boolean hasPartitionStats();
  /**
   * <code>.ballista.protobuf.PartitionStats partition_stats = 3;</code>
   * @return The partitionStats.
   */
  org.ballistacompute.protobuf.PartitionStats getPartitionStats();
  /**
   * <code>.ballista.protobuf.PartitionStats partition_stats = 3;</code>
   */
  org.ballistacompute.protobuf.PartitionStatsOrBuilder getPartitionStatsOrBuilder();

  /**
   * <code>string path = 4;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 4;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
