// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface PollWorkParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.PollWorkParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.ExecutorRegistration metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.ballista.protobuf.ExecutorRegistration metadata = 1;</code>
   * @return The metadata.
   */
  org.ballistacompute.protobuf.ExecutorRegistration getMetadata();
  /**
   * <code>.ballista.protobuf.ExecutorRegistration metadata = 1;</code>
   */
  org.ballistacompute.protobuf.ExecutorRegistrationOrBuilder getMetadataOrBuilder();

  /**
   * <code>bool can_accept_task = 2;</code>
   * @return The canAcceptTask.
   */
  boolean getCanAcceptTask();

  /**
   * <pre>
   * All tasks must be reported until they reach the failed or completed state
   * </pre>
   *
   * <code>repeated .ballista.protobuf.TaskStatus task_status = 3;</code>
   */
  java.util.List<org.ballistacompute.protobuf.TaskStatus> 
      getTaskStatusList();
  /**
   * <pre>
   * All tasks must be reported until they reach the failed or completed state
   * </pre>
   *
   * <code>repeated .ballista.protobuf.TaskStatus task_status = 3;</code>
   */
  org.ballistacompute.protobuf.TaskStatus getTaskStatus(int index);
  /**
   * <pre>
   * All tasks must be reported until they reach the failed or completed state
   * </pre>
   *
   * <code>repeated .ballista.protobuf.TaskStatus task_status = 3;</code>
   */
  int getTaskStatusCount();
  /**
   * <pre>
   * All tasks must be reported until they reach the failed or completed state
   * </pre>
   *
   * <code>repeated .ballista.protobuf.TaskStatus task_status = 3;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.TaskStatusOrBuilder> 
      getTaskStatusOrBuilderList();
  /**
   * <pre>
   * All tasks must be reported until they reach the failed or completed state
   * </pre>
   *
   * <code>repeated .ballista.protobuf.TaskStatus task_status = 3;</code>
   */
  org.ballistacompute.protobuf.TaskStatusOrBuilder getTaskStatusOrBuilder(
      int index);
}
