// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

/**
 * Protobuf type {@code ballista.protobuf.RepartitionNode}
 */
public final class RepartitionNode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ballista.protobuf.RepartitionNode)
    RepartitionNodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RepartitionNode.newBuilder() to construct.
  private RepartitionNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepartitionNode() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RepartitionNode();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RepartitionNode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.ballistacompute.protobuf.LogicalPlanNode.Builder subBuilder = null;
            if (input_ != null) {
              subBuilder = input_.toBuilder();
            }
            input_ = input.readMessage(org.ballistacompute.protobuf.LogicalPlanNode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(input_);
              input_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            partitionMethod_ = input.readUInt64();
            partitionMethodCase_ = 2;
            break;
          }
          case 26: {
            org.ballistacompute.protobuf.HashRepartition.Builder subBuilder = null;
            if (partitionMethodCase_ == 3) {
              subBuilder = ((org.ballistacompute.protobuf.HashRepartition) partitionMethod_).toBuilder();
            }
            partitionMethod_ =
                input.readMessage(org.ballistacompute.protobuf.HashRepartition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.ballistacompute.protobuf.HashRepartition) partitionMethod_);
              partitionMethod_ = subBuilder.buildPartial();
            }
            partitionMethodCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_RepartitionNode_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_RepartitionNode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ballistacompute.protobuf.RepartitionNode.class, org.ballistacompute.protobuf.RepartitionNode.Builder.class);
  }

  private int partitionMethodCase_ = 0;
  private java.lang.Object partitionMethod_;
  public enum PartitionMethodCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ROUND_ROBIN(2),
    HASH(3),
    PARTITIONMETHOD_NOT_SET(0);
    private final int value;
    private PartitionMethodCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PartitionMethodCase valueOf(int value) {
      return forNumber(value);
    }

    public static PartitionMethodCase forNumber(int value) {
      switch (value) {
        case 2: return ROUND_ROBIN;
        case 3: return HASH;
        case 0: return PARTITIONMETHOD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PartitionMethodCase
  getPartitionMethodCase() {
    return PartitionMethodCase.forNumber(
        partitionMethodCase_);
  }

  public static final int INPUT_FIELD_NUMBER = 1;
  private org.ballistacompute.protobuf.LogicalPlanNode input_;
  /**
   * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
   * @return Whether the input field is set.
   */
  @java.lang.Override
  public boolean hasInput() {
    return input_ != null;
  }
  /**
   * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
   * @return The input.
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.LogicalPlanNode getInput() {
    return input_ == null ? org.ballistacompute.protobuf.LogicalPlanNode.getDefaultInstance() : input_;
  }
  /**
   * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder getInputOrBuilder() {
    return getInput();
  }

  public static final int ROUND_ROBIN_FIELD_NUMBER = 2;
  /**
   * <code>uint64 round_robin = 2;</code>
   * @return Whether the roundRobin field is set.
   */
  @java.lang.Override
  public boolean hasRoundRobin() {
    return partitionMethodCase_ == 2;
  }
  /**
   * <code>uint64 round_robin = 2;</code>
   * @return The roundRobin.
   */
  @java.lang.Override
  public long getRoundRobin() {
    if (partitionMethodCase_ == 2) {
      return (java.lang.Long) partitionMethod_;
    }
    return 0L;
  }

  public static final int HASH_FIELD_NUMBER = 3;
  /**
   * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
   * @return Whether the hash field is set.
   */
  @java.lang.Override
  public boolean hasHash() {
    return partitionMethodCase_ == 3;
  }
  /**
   * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
   * @return The hash.
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.HashRepartition getHash() {
    if (partitionMethodCase_ == 3) {
       return (org.ballistacompute.protobuf.HashRepartition) partitionMethod_;
    }
    return org.ballistacompute.protobuf.HashRepartition.getDefaultInstance();
  }
  /**
   * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.HashRepartitionOrBuilder getHashOrBuilder() {
    if (partitionMethodCase_ == 3) {
       return (org.ballistacompute.protobuf.HashRepartition) partitionMethod_;
    }
    return org.ballistacompute.protobuf.HashRepartition.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (input_ != null) {
      output.writeMessage(1, getInput());
    }
    if (partitionMethodCase_ == 2) {
      output.writeUInt64(
          2, (long)((java.lang.Long) partitionMethod_));
    }
    if (partitionMethodCase_ == 3) {
      output.writeMessage(3, (org.ballistacompute.protobuf.HashRepartition) partitionMethod_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (input_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInput());
    }
    if (partitionMethodCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            2, (long)((java.lang.Long) partitionMethod_));
    }
    if (partitionMethodCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.ballistacompute.protobuf.HashRepartition) partitionMethod_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ballistacompute.protobuf.RepartitionNode)) {
      return super.equals(obj);
    }
    org.ballistacompute.protobuf.RepartitionNode other = (org.ballistacompute.protobuf.RepartitionNode) obj;

    if (hasInput() != other.hasInput()) return false;
    if (hasInput()) {
      if (!getInput()
          .equals(other.getInput())) return false;
    }
    if (!getPartitionMethodCase().equals(other.getPartitionMethodCase())) return false;
    switch (partitionMethodCase_) {
      case 2:
        if (getRoundRobin()
            != other.getRoundRobin()) return false;
        break;
      case 3:
        if (!getHash()
            .equals(other.getHash())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInput()) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
    }
    switch (partitionMethodCase_) {
      case 2:
        hash = (37 * hash) + ROUND_ROBIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRoundRobin());
        break;
      case 3:
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHash().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.RepartitionNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ballistacompute.protobuf.RepartitionNode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ballista.protobuf.RepartitionNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ballista.protobuf.RepartitionNode)
      org.ballistacompute.protobuf.RepartitionNodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_RepartitionNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_RepartitionNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ballistacompute.protobuf.RepartitionNode.class, org.ballistacompute.protobuf.RepartitionNode.Builder.class);
    }

    // Construct using org.ballistacompute.protobuf.RepartitionNode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (inputBuilder_ == null) {
        input_ = null;
      } else {
        input_ = null;
        inputBuilder_ = null;
      }
      partitionMethodCase_ = 0;
      partitionMethod_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_RepartitionNode_descriptor;
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.RepartitionNode getDefaultInstanceForType() {
      return org.ballistacompute.protobuf.RepartitionNode.getDefaultInstance();
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.RepartitionNode build() {
      org.ballistacompute.protobuf.RepartitionNode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.RepartitionNode buildPartial() {
      org.ballistacompute.protobuf.RepartitionNode result = new org.ballistacompute.protobuf.RepartitionNode(this);
      if (inputBuilder_ == null) {
        result.input_ = input_;
      } else {
        result.input_ = inputBuilder_.build();
      }
      if (partitionMethodCase_ == 2) {
        result.partitionMethod_ = partitionMethod_;
      }
      if (partitionMethodCase_ == 3) {
        if (hashBuilder_ == null) {
          result.partitionMethod_ = partitionMethod_;
        } else {
          result.partitionMethod_ = hashBuilder_.build();
        }
      }
      result.partitionMethodCase_ = partitionMethodCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ballistacompute.protobuf.RepartitionNode) {
        return mergeFrom((org.ballistacompute.protobuf.RepartitionNode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ballistacompute.protobuf.RepartitionNode other) {
      if (other == org.ballistacompute.protobuf.RepartitionNode.getDefaultInstance()) return this;
      if (other.hasInput()) {
        mergeInput(other.getInput());
      }
      switch (other.getPartitionMethodCase()) {
        case ROUND_ROBIN: {
          setRoundRobin(other.getRoundRobin());
          break;
        }
        case HASH: {
          mergeHash(other.getHash());
          break;
        }
        case PARTITIONMETHOD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.ballistacompute.protobuf.RepartitionNode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.ballistacompute.protobuf.RepartitionNode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int partitionMethodCase_ = 0;
    private java.lang.Object partitionMethod_;
    public PartitionMethodCase
        getPartitionMethodCase() {
      return PartitionMethodCase.forNumber(
          partitionMethodCase_);
    }

    public Builder clearPartitionMethod() {
      partitionMethodCase_ = 0;
      partitionMethod_ = null;
      onChanged();
      return this;
    }


    private org.ballistacompute.protobuf.LogicalPlanNode input_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.ballistacompute.protobuf.LogicalPlanNode, org.ballistacompute.protobuf.LogicalPlanNode.Builder, org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder> inputBuilder_;
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     * @return Whether the input field is set.
     */
    public boolean hasInput() {
      return inputBuilder_ != null || input_ != null;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     * @return The input.
     */
    public org.ballistacompute.protobuf.LogicalPlanNode getInput() {
      if (inputBuilder_ == null) {
        return input_ == null ? org.ballistacompute.protobuf.LogicalPlanNode.getDefaultInstance() : input_;
      } else {
        return inputBuilder_.getMessage();
      }
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder setInput(org.ballistacompute.protobuf.LogicalPlanNode value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
        onChanged();
      } else {
        inputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder setInput(
        org.ballistacompute.protobuf.LogicalPlanNode.Builder builderForValue) {
      if (inputBuilder_ == null) {
        input_ = builderForValue.build();
        onChanged();
      } else {
        inputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder mergeInput(org.ballistacompute.protobuf.LogicalPlanNode value) {
      if (inputBuilder_ == null) {
        if (input_ != null) {
          input_ =
            org.ballistacompute.protobuf.LogicalPlanNode.newBuilder(input_).mergeFrom(value).buildPartial();
        } else {
          input_ = value;
        }
        onChanged();
      } else {
        inputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder clearInput() {
      if (inputBuilder_ == null) {
        input_ = null;
        onChanged();
      } else {
        input_ = null;
        inputBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public org.ballistacompute.protobuf.LogicalPlanNode.Builder getInputBuilder() {
      
      onChanged();
      return getInputFieldBuilder().getBuilder();
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder getInputOrBuilder() {
      if (inputBuilder_ != null) {
        return inputBuilder_.getMessageOrBuilder();
      } else {
        return input_ == null ?
            org.ballistacompute.protobuf.LogicalPlanNode.getDefaultInstance() : input_;
      }
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.ballistacompute.protobuf.LogicalPlanNode, org.ballistacompute.protobuf.LogicalPlanNode.Builder, org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder> 
        getInputFieldBuilder() {
      if (inputBuilder_ == null) {
        inputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.ballistacompute.protobuf.LogicalPlanNode, org.ballistacompute.protobuf.LogicalPlanNode.Builder, org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder>(
                getInput(),
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      return inputBuilder_;
    }

    /**
     * <code>uint64 round_robin = 2;</code>
     * @return Whether the roundRobin field is set.
     */
    public boolean hasRoundRobin() {
      return partitionMethodCase_ == 2;
    }
    /**
     * <code>uint64 round_robin = 2;</code>
     * @return The roundRobin.
     */
    public long getRoundRobin() {
      if (partitionMethodCase_ == 2) {
        return (java.lang.Long) partitionMethod_;
      }
      return 0L;
    }
    /**
     * <code>uint64 round_robin = 2;</code>
     * @param value The roundRobin to set.
     * @return This builder for chaining.
     */
    public Builder setRoundRobin(long value) {
      partitionMethodCase_ = 2;
      partitionMethod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 round_robin = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundRobin() {
      if (partitionMethodCase_ == 2) {
        partitionMethodCase_ = 0;
        partitionMethod_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.ballistacompute.protobuf.HashRepartition, org.ballistacompute.protobuf.HashRepartition.Builder, org.ballistacompute.protobuf.HashRepartitionOrBuilder> hashBuilder_;
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     * @return Whether the hash field is set.
     */
    @java.lang.Override
    public boolean hasHash() {
      return partitionMethodCase_ == 3;
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     * @return The hash.
     */
    @java.lang.Override
    public org.ballistacompute.protobuf.HashRepartition getHash() {
      if (hashBuilder_ == null) {
        if (partitionMethodCase_ == 3) {
          return (org.ballistacompute.protobuf.HashRepartition) partitionMethod_;
        }
        return org.ballistacompute.protobuf.HashRepartition.getDefaultInstance();
      } else {
        if (partitionMethodCase_ == 3) {
          return hashBuilder_.getMessage();
        }
        return org.ballistacompute.protobuf.HashRepartition.getDefaultInstance();
      }
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    public Builder setHash(org.ballistacompute.protobuf.HashRepartition value) {
      if (hashBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        partitionMethod_ = value;
        onChanged();
      } else {
        hashBuilder_.setMessage(value);
      }
      partitionMethodCase_ = 3;
      return this;
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    public Builder setHash(
        org.ballistacompute.protobuf.HashRepartition.Builder builderForValue) {
      if (hashBuilder_ == null) {
        partitionMethod_ = builderForValue.build();
        onChanged();
      } else {
        hashBuilder_.setMessage(builderForValue.build());
      }
      partitionMethodCase_ = 3;
      return this;
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    public Builder mergeHash(org.ballistacompute.protobuf.HashRepartition value) {
      if (hashBuilder_ == null) {
        if (partitionMethodCase_ == 3 &&
            partitionMethod_ != org.ballistacompute.protobuf.HashRepartition.getDefaultInstance()) {
          partitionMethod_ = org.ballistacompute.protobuf.HashRepartition.newBuilder((org.ballistacompute.protobuf.HashRepartition) partitionMethod_)
              .mergeFrom(value).buildPartial();
        } else {
          partitionMethod_ = value;
        }
        onChanged();
      } else {
        if (partitionMethodCase_ == 3) {
          hashBuilder_.mergeFrom(value);
        }
        hashBuilder_.setMessage(value);
      }
      partitionMethodCase_ = 3;
      return this;
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    public Builder clearHash() {
      if (hashBuilder_ == null) {
        if (partitionMethodCase_ == 3) {
          partitionMethodCase_ = 0;
          partitionMethod_ = null;
          onChanged();
        }
      } else {
        if (partitionMethodCase_ == 3) {
          partitionMethodCase_ = 0;
          partitionMethod_ = null;
        }
        hashBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    public org.ballistacompute.protobuf.HashRepartition.Builder getHashBuilder() {
      return getHashFieldBuilder().getBuilder();
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    @java.lang.Override
    public org.ballistacompute.protobuf.HashRepartitionOrBuilder getHashOrBuilder() {
      if ((partitionMethodCase_ == 3) && (hashBuilder_ != null)) {
        return hashBuilder_.getMessageOrBuilder();
      } else {
        if (partitionMethodCase_ == 3) {
          return (org.ballistacompute.protobuf.HashRepartition) partitionMethod_;
        }
        return org.ballistacompute.protobuf.HashRepartition.getDefaultInstance();
      }
    }
    /**
     * <code>.ballista.protobuf.HashRepartition hash = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.ballistacompute.protobuf.HashRepartition, org.ballistacompute.protobuf.HashRepartition.Builder, org.ballistacompute.protobuf.HashRepartitionOrBuilder> 
        getHashFieldBuilder() {
      if (hashBuilder_ == null) {
        if (!(partitionMethodCase_ == 3)) {
          partitionMethod_ = org.ballistacompute.protobuf.HashRepartition.getDefaultInstance();
        }
        hashBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.ballistacompute.protobuf.HashRepartition, org.ballistacompute.protobuf.HashRepartition.Builder, org.ballistacompute.protobuf.HashRepartitionOrBuilder>(
                (org.ballistacompute.protobuf.HashRepartition) partitionMethod_,
                getParentForChildren(),
                isClean());
        partitionMethod_ = null;
      }
      partitionMethodCase_ = 3;
      onChanged();;
      return hashBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ballista.protobuf.RepartitionNode)
  }

  // @@protoc_insertion_point(class_scope:ballista.protobuf.RepartitionNode)
  private static final org.ballistacompute.protobuf.RepartitionNode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ballistacompute.protobuf.RepartitionNode();
  }

  public static org.ballistacompute.protobuf.RepartitionNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepartitionNode>
      PARSER = new com.google.protobuf.AbstractParser<RepartitionNode>() {
    @java.lang.Override
    public RepartitionNode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RepartitionNode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RepartitionNode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepartitionNode> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ballistacompute.protobuf.RepartitionNode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

