// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface RunningTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.RunningTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string executor_id = 1;</code>
   * @return The executorId.
   */
  java.lang.String getExecutorId();
  /**
   * <code>string executor_id = 1;</code>
   * @return The bytes for executorId.
   */
  com.google.protobuf.ByteString
      getExecutorIdBytes();
}
