// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface SortExecNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.SortExecNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.PhysicalPlanNode input = 1;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.ballista.protobuf.PhysicalPlanNode input = 1;</code>
   * @return The input.
   */
  org.ballistacompute.protobuf.PhysicalPlanNode getInput();
  /**
   * <code>.ballista.protobuf.PhysicalPlanNode input = 1;</code>
   */
  org.ballistacompute.protobuf.PhysicalPlanNodeOrBuilder getInputOrBuilder();

  /**
   * <code>repeated .ballista.protobuf.PhysicalExprNode expr = 2;</code>
   */
  java.util.List<org.ballistacompute.protobuf.PhysicalExprNode> 
      getExprList();
  /**
   * <code>repeated .ballista.protobuf.PhysicalExprNode expr = 2;</code>
   */
  org.ballistacompute.protobuf.PhysicalExprNode getExpr(int index);
  /**
   * <code>repeated .ballista.protobuf.PhysicalExprNode expr = 2;</code>
   */
  int getExprCount();
  /**
   * <code>repeated .ballista.protobuf.PhysicalExprNode expr = 2;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.PhysicalExprNodeOrBuilder> 
      getExprOrBuilderList();
  /**
   * <code>repeated .ballista.protobuf.PhysicalExprNode expr = 2;</code>
   */
  org.ballistacompute.protobuf.PhysicalExprNodeOrBuilder getExprOrBuilder(
      int index);
}
