// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

/**
 * Protobuf type {@code ballista.protobuf.SortNode}
 */
public final class SortNode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ballista.protobuf.SortNode)
    SortNodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SortNode.newBuilder() to construct.
  private SortNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SortNode() {
    expr_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SortNode();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SortNode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.ballistacompute.protobuf.LogicalPlanNode.Builder subBuilder = null;
            if (input_ != null) {
              subBuilder = input_.toBuilder();
            }
            input_ = input.readMessage(org.ballistacompute.protobuf.LogicalPlanNode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(input_);
              input_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              expr_ = new java.util.ArrayList<org.ballistacompute.protobuf.LogicalExprNode>();
              mutable_bitField0_ |= 0x00000001;
            }
            expr_.add(
                input.readMessage(org.ballistacompute.protobuf.LogicalExprNode.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        expr_ = java.util.Collections.unmodifiableList(expr_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_SortNode_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_SortNode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ballistacompute.protobuf.SortNode.class, org.ballistacompute.protobuf.SortNode.Builder.class);
  }

  public static final int INPUT_FIELD_NUMBER = 1;
  private org.ballistacompute.protobuf.LogicalPlanNode input_;
  /**
   * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
   * @return Whether the input field is set.
   */
  @java.lang.Override
  public boolean hasInput() {
    return input_ != null;
  }
  /**
   * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
   * @return The input.
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.LogicalPlanNode getInput() {
    return input_ == null ? org.ballistacompute.protobuf.LogicalPlanNode.getDefaultInstance() : input_;
  }
  /**
   * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder getInputOrBuilder() {
    return getInput();
  }

  public static final int EXPR_FIELD_NUMBER = 2;
  private java.util.List<org.ballistacompute.protobuf.LogicalExprNode> expr_;
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.ballistacompute.protobuf.LogicalExprNode> getExprList() {
    return expr_;
  }
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.ballistacompute.protobuf.LogicalExprNodeOrBuilder> 
      getExprOrBuilderList() {
    return expr_;
  }
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
   */
  @java.lang.Override
  public int getExprCount() {
    return expr_.size();
  }
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.LogicalExprNode getExpr(int index) {
    return expr_.get(index);
  }
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
   */
  @java.lang.Override
  public org.ballistacompute.protobuf.LogicalExprNodeOrBuilder getExprOrBuilder(
      int index) {
    return expr_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (input_ != null) {
      output.writeMessage(1, getInput());
    }
    for (int i = 0; i < expr_.size(); i++) {
      output.writeMessage(2, expr_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (input_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInput());
    }
    for (int i = 0; i < expr_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, expr_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ballistacompute.protobuf.SortNode)) {
      return super.equals(obj);
    }
    org.ballistacompute.protobuf.SortNode other = (org.ballistacompute.protobuf.SortNode) obj;

    if (hasInput() != other.hasInput()) return false;
    if (hasInput()) {
      if (!getInput()
          .equals(other.getInput())) return false;
    }
    if (!getExprList()
        .equals(other.getExprList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInput()) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
    }
    if (getExprCount() > 0) {
      hash = (37 * hash) + EXPR_FIELD_NUMBER;
      hash = (53 * hash) + getExprList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ballistacompute.protobuf.SortNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.SortNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.SortNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ballistacompute.protobuf.SortNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ballistacompute.protobuf.SortNode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ballista.protobuf.SortNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ballista.protobuf.SortNode)
      org.ballistacompute.protobuf.SortNodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_SortNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_SortNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ballistacompute.protobuf.SortNode.class, org.ballistacompute.protobuf.SortNode.Builder.class);
    }

    // Construct using org.ballistacompute.protobuf.SortNode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExprFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (inputBuilder_ == null) {
        input_ = null;
      } else {
        input_ = null;
        inputBuilder_ = null;
      }
      if (exprBuilder_ == null) {
        expr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        exprBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ballistacompute.protobuf.BallistaProto.internal_static_ballista_protobuf_SortNode_descriptor;
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.SortNode getDefaultInstanceForType() {
      return org.ballistacompute.protobuf.SortNode.getDefaultInstance();
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.SortNode build() {
      org.ballistacompute.protobuf.SortNode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ballistacompute.protobuf.SortNode buildPartial() {
      org.ballistacompute.protobuf.SortNode result = new org.ballistacompute.protobuf.SortNode(this);
      int from_bitField0_ = bitField0_;
      if (inputBuilder_ == null) {
        result.input_ = input_;
      } else {
        result.input_ = inputBuilder_.build();
      }
      if (exprBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          expr_ = java.util.Collections.unmodifiableList(expr_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.expr_ = expr_;
      } else {
        result.expr_ = exprBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ballistacompute.protobuf.SortNode) {
        return mergeFrom((org.ballistacompute.protobuf.SortNode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ballistacompute.protobuf.SortNode other) {
      if (other == org.ballistacompute.protobuf.SortNode.getDefaultInstance()) return this;
      if (other.hasInput()) {
        mergeInput(other.getInput());
      }
      if (exprBuilder_ == null) {
        if (!other.expr_.isEmpty()) {
          if (expr_.isEmpty()) {
            expr_ = other.expr_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExprIsMutable();
            expr_.addAll(other.expr_);
          }
          onChanged();
        }
      } else {
        if (!other.expr_.isEmpty()) {
          if (exprBuilder_.isEmpty()) {
            exprBuilder_.dispose();
            exprBuilder_ = null;
            expr_ = other.expr_;
            bitField0_ = (bitField0_ & ~0x00000001);
            exprBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExprFieldBuilder() : null;
          } else {
            exprBuilder_.addAllMessages(other.expr_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.ballistacompute.protobuf.SortNode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.ballistacompute.protobuf.SortNode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.ballistacompute.protobuf.LogicalPlanNode input_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.ballistacompute.protobuf.LogicalPlanNode, org.ballistacompute.protobuf.LogicalPlanNode.Builder, org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder> inputBuilder_;
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     * @return Whether the input field is set.
     */
    public boolean hasInput() {
      return inputBuilder_ != null || input_ != null;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     * @return The input.
     */
    public org.ballistacompute.protobuf.LogicalPlanNode getInput() {
      if (inputBuilder_ == null) {
        return input_ == null ? org.ballistacompute.protobuf.LogicalPlanNode.getDefaultInstance() : input_;
      } else {
        return inputBuilder_.getMessage();
      }
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder setInput(org.ballistacompute.protobuf.LogicalPlanNode value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
        onChanged();
      } else {
        inputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder setInput(
        org.ballistacompute.protobuf.LogicalPlanNode.Builder builderForValue) {
      if (inputBuilder_ == null) {
        input_ = builderForValue.build();
        onChanged();
      } else {
        inputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder mergeInput(org.ballistacompute.protobuf.LogicalPlanNode value) {
      if (inputBuilder_ == null) {
        if (input_ != null) {
          input_ =
            org.ballistacompute.protobuf.LogicalPlanNode.newBuilder(input_).mergeFrom(value).buildPartial();
        } else {
          input_ = value;
        }
        onChanged();
      } else {
        inputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public Builder clearInput() {
      if (inputBuilder_ == null) {
        input_ = null;
        onChanged();
      } else {
        input_ = null;
        inputBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public org.ballistacompute.protobuf.LogicalPlanNode.Builder getInputBuilder() {
      
      onChanged();
      return getInputFieldBuilder().getBuilder();
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    public org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder getInputOrBuilder() {
      if (inputBuilder_ != null) {
        return inputBuilder_.getMessageOrBuilder();
      } else {
        return input_ == null ?
            org.ballistacompute.protobuf.LogicalPlanNode.getDefaultInstance() : input_;
      }
    }
    /**
     * <code>.ballista.protobuf.LogicalPlanNode input = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.ballistacompute.protobuf.LogicalPlanNode, org.ballistacompute.protobuf.LogicalPlanNode.Builder, org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder> 
        getInputFieldBuilder() {
      if (inputBuilder_ == null) {
        inputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.ballistacompute.protobuf.LogicalPlanNode, org.ballistacompute.protobuf.LogicalPlanNode.Builder, org.ballistacompute.protobuf.LogicalPlanNodeOrBuilder>(
                getInput(),
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      return inputBuilder_;
    }

    private java.util.List<org.ballistacompute.protobuf.LogicalExprNode> expr_ =
      java.util.Collections.emptyList();
    private void ensureExprIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        expr_ = new java.util.ArrayList<org.ballistacompute.protobuf.LogicalExprNode>(expr_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.ballistacompute.protobuf.LogicalExprNode, org.ballistacompute.protobuf.LogicalExprNode.Builder, org.ballistacompute.protobuf.LogicalExprNodeOrBuilder> exprBuilder_;

    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public java.util.List<org.ballistacompute.protobuf.LogicalExprNode> getExprList() {
      if (exprBuilder_ == null) {
        return java.util.Collections.unmodifiableList(expr_);
      } else {
        return exprBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public int getExprCount() {
      if (exprBuilder_ == null) {
        return expr_.size();
      } else {
        return exprBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public org.ballistacompute.protobuf.LogicalExprNode getExpr(int index) {
      if (exprBuilder_ == null) {
        return expr_.get(index);
      } else {
        return exprBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder setExpr(
        int index, org.ballistacompute.protobuf.LogicalExprNode value) {
      if (exprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprIsMutable();
        expr_.set(index, value);
        onChanged();
      } else {
        exprBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder setExpr(
        int index, org.ballistacompute.protobuf.LogicalExprNode.Builder builderForValue) {
      if (exprBuilder_ == null) {
        ensureExprIsMutable();
        expr_.set(index, builderForValue.build());
        onChanged();
      } else {
        exprBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder addExpr(org.ballistacompute.protobuf.LogicalExprNode value) {
      if (exprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprIsMutable();
        expr_.add(value);
        onChanged();
      } else {
        exprBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder addExpr(
        int index, org.ballistacompute.protobuf.LogicalExprNode value) {
      if (exprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprIsMutable();
        expr_.add(index, value);
        onChanged();
      } else {
        exprBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder addExpr(
        org.ballistacompute.protobuf.LogicalExprNode.Builder builderForValue) {
      if (exprBuilder_ == null) {
        ensureExprIsMutable();
        expr_.add(builderForValue.build());
        onChanged();
      } else {
        exprBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder addExpr(
        int index, org.ballistacompute.protobuf.LogicalExprNode.Builder builderForValue) {
      if (exprBuilder_ == null) {
        ensureExprIsMutable();
        expr_.add(index, builderForValue.build());
        onChanged();
      } else {
        exprBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder addAllExpr(
        java.lang.Iterable<? extends org.ballistacompute.protobuf.LogicalExprNode> values) {
      if (exprBuilder_ == null) {
        ensureExprIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, expr_);
        onChanged();
      } else {
        exprBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder clearExpr() {
      if (exprBuilder_ == null) {
        expr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        exprBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public Builder removeExpr(int index) {
      if (exprBuilder_ == null) {
        ensureExprIsMutable();
        expr_.remove(index);
        onChanged();
      } else {
        exprBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public org.ballistacompute.protobuf.LogicalExprNode.Builder getExprBuilder(
        int index) {
      return getExprFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public org.ballistacompute.protobuf.LogicalExprNodeOrBuilder getExprOrBuilder(
        int index) {
      if (exprBuilder_ == null) {
        return expr_.get(index);  } else {
        return exprBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public java.util.List<? extends org.ballistacompute.protobuf.LogicalExprNodeOrBuilder> 
         getExprOrBuilderList() {
      if (exprBuilder_ != null) {
        return exprBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(expr_);
      }
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public org.ballistacompute.protobuf.LogicalExprNode.Builder addExprBuilder() {
      return getExprFieldBuilder().addBuilder(
          org.ballistacompute.protobuf.LogicalExprNode.getDefaultInstance());
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public org.ballistacompute.protobuf.LogicalExprNode.Builder addExprBuilder(
        int index) {
      return getExprFieldBuilder().addBuilder(
          index, org.ballistacompute.protobuf.LogicalExprNode.getDefaultInstance());
    }
    /**
     * <code>repeated .ballista.protobuf.LogicalExprNode expr = 2;</code>
     */
    public java.util.List<org.ballistacompute.protobuf.LogicalExprNode.Builder> 
         getExprBuilderList() {
      return getExprFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.ballistacompute.protobuf.LogicalExprNode, org.ballistacompute.protobuf.LogicalExprNode.Builder, org.ballistacompute.protobuf.LogicalExprNodeOrBuilder> 
        getExprFieldBuilder() {
      if (exprBuilder_ == null) {
        exprBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.ballistacompute.protobuf.LogicalExprNode, org.ballistacompute.protobuf.LogicalExprNode.Builder, org.ballistacompute.protobuf.LogicalExprNodeOrBuilder>(
                expr_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        expr_ = null;
      }
      return exprBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ballista.protobuf.SortNode)
  }

  // @@protoc_insertion_point(class_scope:ballista.protobuf.SortNode)
  private static final org.ballistacompute.protobuf.SortNode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ballistacompute.protobuf.SortNode();
  }

  public static org.ballistacompute.protobuf.SortNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SortNode>
      PARSER = new com.google.protobuf.AbstractParser<SortNode>() {
    @java.lang.Override
    public SortNode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SortNode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SortNode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SortNode> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ballistacompute.protobuf.SortNode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

