// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface WindowFrameBoundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.WindowFrameBound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.WindowFrameBoundType window_frame_bound_type = 1;</code>
   * @return The enum numeric value on the wire for windowFrameBoundType.
   */
  int getWindowFrameBoundTypeValue();
  /**
   * <code>.ballista.protobuf.WindowFrameBoundType window_frame_bound_type = 1;</code>
   * @return The windowFrameBoundType.
   */
  org.ballistacompute.protobuf.WindowFrameBoundType getWindowFrameBoundType();

  /**
   * <code>uint64 value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>uint64 value = 2;</code>
   * @return The value.
   */
  long getValue();

  public org.ballistacompute.protobuf.WindowFrameBound.BoundValueCase getBoundValueCase();
}
