// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ballista.proto

package org.ballistacompute.protobuf;

public interface WindowExprNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ballista.protobuf.WindowExprNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ballista.protobuf.AggregateFunction aggr_function = 1;</code>
   * @return Whether the aggrFunction field is set.
   */
  boolean hasAggrFunction();
  /**
   * <code>.ballista.protobuf.AggregateFunction aggr_function = 1;</code>
   * @return The enum numeric value on the wire for aggrFunction.
   */
  int getAggrFunctionValue();
  /**
   * <code>.ballista.protobuf.AggregateFunction aggr_function = 1;</code>
   * @return The aggrFunction.
   */
  org.ballistacompute.protobuf.AggregateFunction getAggrFunction();

  /**
   * <pre>
   * udaf = 3
   * </pre>
   *
   * <code>.ballista.protobuf.BuiltInWindowFunction built_in_function = 2;</code>
   * @return Whether the builtInFunction field is set.
   */
  boolean hasBuiltInFunction();
  /**
   * <pre>
   * udaf = 3
   * </pre>
   *
   * <code>.ballista.protobuf.BuiltInWindowFunction built_in_function = 2;</code>
   * @return The enum numeric value on the wire for builtInFunction.
   */
  int getBuiltInFunctionValue();
  /**
   * <pre>
   * udaf = 3
   * </pre>
   *
   * <code>.ballista.protobuf.BuiltInWindowFunction built_in_function = 2;</code>
   * @return The builtInFunction.
   */
  org.ballistacompute.protobuf.BuiltInWindowFunction getBuiltInFunction();

  /**
   * <code>.ballista.protobuf.LogicalExprNode expr = 4;</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <code>.ballista.protobuf.LogicalExprNode expr = 4;</code>
   * @return The expr.
   */
  org.ballistacompute.protobuf.LogicalExprNode getExpr();
  /**
   * <code>.ballista.protobuf.LogicalExprNode expr = 4;</code>
   */
  org.ballistacompute.protobuf.LogicalExprNodeOrBuilder getExprOrBuilder();

  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode partition_by = 5;</code>
   */
  java.util.List<org.ballistacompute.protobuf.LogicalExprNode> 
      getPartitionByList();
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode partition_by = 5;</code>
   */
  org.ballistacompute.protobuf.LogicalExprNode getPartitionBy(int index);
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode partition_by = 5;</code>
   */
  int getPartitionByCount();
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode partition_by = 5;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.LogicalExprNodeOrBuilder> 
      getPartitionByOrBuilderList();
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode partition_by = 5;</code>
   */
  org.ballistacompute.protobuf.LogicalExprNodeOrBuilder getPartitionByOrBuilder(
      int index);

  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode order_by = 6;</code>
   */
  java.util.List<org.ballistacompute.protobuf.LogicalExprNode> 
      getOrderByList();
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode order_by = 6;</code>
   */
  org.ballistacompute.protobuf.LogicalExprNode getOrderBy(int index);
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode order_by = 6;</code>
   */
  int getOrderByCount();
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode order_by = 6;</code>
   */
  java.util.List<? extends org.ballistacompute.protobuf.LogicalExprNodeOrBuilder> 
      getOrderByOrBuilderList();
  /**
   * <code>repeated .ballista.protobuf.LogicalExprNode order_by = 6;</code>
   */
  org.ballistacompute.protobuf.LogicalExprNodeOrBuilder getOrderByOrBuilder(
      int index);

  /**
   * <code>.ballista.protobuf.WindowFrame frame = 8;</code>
   * @return Whether the frame field is set.
   */
  boolean hasFrame();
  /**
   * <code>.ballista.protobuf.WindowFrame frame = 8;</code>
   * @return The frame.
   */
  org.ballistacompute.protobuf.WindowFrame getFrame();
  /**
   * <code>.ballista.protobuf.WindowFrame frame = 8;</code>
   */
  org.ballistacompute.protobuf.WindowFrameOrBuilder getFrameOrBuilder();

  public org.ballistacompute.protobuf.WindowExprNode.WindowFunctionCase getWindowFunctionCase();

  public org.ballistacompute.protobuf.WindowExprNode.WindowFrameCase getWindowFrameCase();
}
