// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface ColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.Column)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.plan.protobuf.ColumnRelation relation = 2;</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <code>.plan.protobuf.ColumnRelation relation = 2;</code>
   * @return The relation.
   */
  org.blaze.protobuf.ColumnRelation getRelation();
  /**
   * <code>.plan.protobuf.ColumnRelation relation = 2;</code>
   */
  org.blaze.protobuf.ColumnRelationOrBuilder getRelationOrBuilder();
}
