// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface PartitionStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.PartitionStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 num_rows = 1;</code>
   * @return The numRows.
   */
  long getNumRows();

  /**
   * <code>int64 num_batches = 2;</code>
   * @return The numBatches.
   */
  long getNumBatches();

  /**
   * <code>int64 num_bytes = 3;</code>
   * @return The numBytes.
   */
  long getNumBytes();

  /**
   * <code>repeated .plan.protobuf.ColumnStats column_stats = 4;</code>
   */
  java.util.List<org.blaze.protobuf.ColumnStats> 
      getColumnStatsList();
  /**
   * <code>repeated .plan.protobuf.ColumnStats column_stats = 4;</code>
   */
  org.blaze.protobuf.ColumnStats getColumnStats(int index);
  /**
   * <code>repeated .plan.protobuf.ColumnStats column_stats = 4;</code>
   */
  int getColumnStatsCount();
  /**
   * <code>repeated .plan.protobuf.ColumnStats column_stats = 4;</code>
   */
  java.util.List<? extends org.blaze.protobuf.ColumnStatsOrBuilder> 
      getColumnStatsOrBuilderList();
  /**
   * <code>repeated .plan.protobuf.ColumnStats column_stats = 4;</code>
   */
  org.blaze.protobuf.ColumnStatsOrBuilder getColumnStatsOrBuilder(
      int index);
}
