// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface PartitionedFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.PartitionedFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>uint64 size = 2;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>uint64 last_modified_ns = 3;</code>
   * @return The lastModifiedNs.
   */
  long getLastModifiedNs();

  /**
   * <code>repeated .plan.protobuf.ScalarValue partition_values = 4;</code>
   */
  java.util.List<org.blaze.protobuf.ScalarValue> 
      getPartitionValuesList();
  /**
   * <code>repeated .plan.protobuf.ScalarValue partition_values = 4;</code>
   */
  org.blaze.protobuf.ScalarValue getPartitionValues(int index);
  /**
   * <code>repeated .plan.protobuf.ScalarValue partition_values = 4;</code>
   */
  int getPartitionValuesCount();
  /**
   * <code>repeated .plan.protobuf.ScalarValue partition_values = 4;</code>
   */
  java.util.List<? extends org.blaze.protobuf.ScalarValueOrBuilder> 
      getPartitionValuesOrBuilderList();
  /**
   * <code>repeated .plan.protobuf.ScalarValue partition_values = 4;</code>
   */
  org.blaze.protobuf.ScalarValueOrBuilder getPartitionValuesOrBuilder(
      int index);
}
