// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface PhysicalColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.PhysicalColumn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 index = 2;</code>
   * @return The index.
   */
  int getIndex();
}
