// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface ProjectionExecNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.ProjectionExecNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   * @return The input.
   */
  org.blaze.protobuf.PhysicalPlanNode getInput();
  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   */
  org.blaze.protobuf.PhysicalPlanNodeOrBuilder getInputOrBuilder();

  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode expr = 2;</code>
   */
  java.util.List<org.blaze.protobuf.PhysicalExprNode> 
      getExprList();
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode expr = 2;</code>
   */
  org.blaze.protobuf.PhysicalExprNode getExpr(int index);
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode expr = 2;</code>
   */
  int getExprCount();
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode expr = 2;</code>
   */
  java.util.List<? extends org.blaze.protobuf.PhysicalExprNodeOrBuilder> 
      getExprOrBuilderList();
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode expr = 2;</code>
   */
  org.blaze.protobuf.PhysicalExprNodeOrBuilder getExprOrBuilder(
      int index);

  /**
   * <code>repeated string expr_name = 3;</code>
   * @return A list containing the exprName.
   */
  java.util.List<java.lang.String>
      getExprNameList();
  /**
   * <code>repeated string expr_name = 3;</code>
   * @return The count of exprName.
   */
  int getExprNameCount();
  /**
   * <code>repeated string expr_name = 3;</code>
   * @param index The index of the element to return.
   * @return The exprName at the given index.
   */
  java.lang.String getExprName(int index);
  /**
   * <code>repeated string expr_name = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the exprName at the given index.
   */
  com.google.protobuf.ByteString
      getExprNameBytes(int index);
}
