// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface RepartitionExecNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.RepartitionExecNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   * @return The input.
   */
  org.blaze.protobuf.PhysicalPlanNode getInput();
  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   */
  org.blaze.protobuf.PhysicalPlanNodeOrBuilder getInputOrBuilder();

  /**
   * <code>uint64 round_robin = 2;</code>
   * @return Whether the roundRobin field is set.
   */
  boolean hasRoundRobin();
  /**
   * <code>uint64 round_robin = 2;</code>
   * @return The roundRobin.
   */
  long getRoundRobin();

  /**
   * <code>.plan.protobuf.PhysicalHashRepartition hash = 3;</code>
   * @return Whether the hash field is set.
   */
  boolean hasHash();
  /**
   * <code>.plan.protobuf.PhysicalHashRepartition hash = 3;</code>
   * @return The hash.
   */
  org.blaze.protobuf.PhysicalHashRepartition getHash();
  /**
   * <code>.plan.protobuf.PhysicalHashRepartition hash = 3;</code>
   */
  org.blaze.protobuf.PhysicalHashRepartitionOrBuilder getHashOrBuilder();

  /**
   * <code>uint64 unknown = 4;</code>
   * @return Whether the unknown field is set.
   */
  boolean hasUnknown();
  /**
   * <code>uint64 unknown = 4;</code>
   * @return The unknown.
   */
  long getUnknown();

  public org.blaze.protobuf.RepartitionExecNode.PartitionMethodCase getPartitionMethodCase();
}
