// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface ShuffleReaderExecNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.ShuffleReaderExecNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.plan.protobuf.Schema schema = 2;</code>
   * @return Whether the schema field is set.
   */
  boolean hasSchema();
  /**
   * <code>.plan.protobuf.Schema schema = 2;</code>
   * @return The schema.
   */
  org.blaze.protobuf.Schema getSchema();
  /**
   * <code>.plan.protobuf.Schema schema = 2;</code>
   */
  org.blaze.protobuf.SchemaOrBuilder getSchemaOrBuilder();
}
