// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

/**
 * Protobuf enum {@code plan.protobuf.TimeUnit}
 */
public enum TimeUnit
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Second = 0;</code>
   */
  Second(0),
  /**
   * <code>TimeMillisecond = 1;</code>
   */
  TimeMillisecond(1),
  /**
   * <code>Microsecond = 2;</code>
   */
  Microsecond(2),
  /**
   * <code>Nanosecond = 3;</code>
   */
  Nanosecond(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Second = 0;</code>
   */
  public static final int Second_VALUE = 0;
  /**
   * <code>TimeMillisecond = 1;</code>
   */
  public static final int TimeMillisecond_VALUE = 1;
  /**
   * <code>Microsecond = 2;</code>
   */
  public static final int Microsecond_VALUE = 2;
  /**
   * <code>Nanosecond = 3;</code>
   */
  public static final int Nanosecond_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TimeUnit valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TimeUnit forNumber(int value) {
    switch (value) {
      case 0: return Second;
      case 1: return TimeMillisecond;
      case 2: return Microsecond;
      case 3: return Nanosecond;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TimeUnit>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TimeUnit> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TimeUnit>() {
          public TimeUnit findValueByNumber(int number) {
            return TimeUnit.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.blaze.protobuf.BlazeProto.getDescriptor().getEnumTypes().get(8);
  }

  private static final TimeUnit[] VALUES = values();

  public static TimeUnit valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TimeUnit(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:plan.protobuf.TimeUnit)
}

