// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/plan.proto

package org.blaze.protobuf;

public interface WindowAggExecNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plan.protobuf.WindowAggExecNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   * @return The input.
   */
  org.blaze.protobuf.PhysicalPlanNode getInput();
  /**
   * <code>.plan.protobuf.PhysicalPlanNode input = 1;</code>
   */
  org.blaze.protobuf.PhysicalPlanNodeOrBuilder getInputOrBuilder();

  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode window_expr = 2;</code>
   */
  java.util.List<org.blaze.protobuf.PhysicalExprNode> 
      getWindowExprList();
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode window_expr = 2;</code>
   */
  org.blaze.protobuf.PhysicalExprNode getWindowExpr(int index);
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode window_expr = 2;</code>
   */
  int getWindowExprCount();
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode window_expr = 2;</code>
   */
  java.util.List<? extends org.blaze.protobuf.PhysicalExprNodeOrBuilder> 
      getWindowExprOrBuilderList();
  /**
   * <code>repeated .plan.protobuf.PhysicalExprNode window_expr = 2;</code>
   */
  org.blaze.protobuf.PhysicalExprNodeOrBuilder getWindowExprOrBuilder(
      int index);

  /**
   * <code>repeated string window_expr_name = 3;</code>
   * @return A list containing the windowExprName.
   */
  java.util.List<java.lang.String>
      getWindowExprNameList();
  /**
   * <code>repeated string window_expr_name = 3;</code>
   * @return The count of windowExprName.
   */
  int getWindowExprNameCount();
  /**
   * <code>repeated string window_expr_name = 3;</code>
   * @param index The index of the element to return.
   * @return The windowExprName at the given index.
   */
  java.lang.String getWindowExprName(int index);
  /**
   * <code>repeated string window_expr_name = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the windowExprName at the given index.
   */
  com.google.protobuf.ByteString
      getWindowExprNameBytes(int index);

  /**
   * <code>.plan.protobuf.Schema input_schema = 4;</code>
   * @return Whether the inputSchema field is set.
   */
  boolean hasInputSchema();
  /**
   * <code>.plan.protobuf.Schema input_schema = 4;</code>
   * @return The inputSchema.
   */
  org.blaze.protobuf.Schema getInputSchema();
  /**
   * <code>.plan.protobuf.Schema input_schema = 4;</code>
   */
  org.blaze.protobuf.SchemaOrBuilder getInputSchemaOrBuilder();
}
